export enum ServerEventType {
  JOINROOM = 'JOINROOM',
  LEAVEROOM = 'LEAVEROOM',
  ROOMLIST = 'ROOMLIST',
  SETMONEY = 'SETMONEY',
  SETNAME = 'SETNAME',
  CREATE_ROOM = 'CREATE_ROOM',
  PAY_MOENY = 'PAY_MOENY',
}

export enum ClientEventType {
  MESSAGE = 'MESSAGE',
  ROOMLIST = 'ROOMLIST',
  SET_UID = 'SET_UID',
  PLAYERINFO = 'PLAYERINFO',
}
